import re

with open('frontend/index.html', 'r') as f:
    content = f.read()

# Find the second and third script blocks
# script2: line 901
script2_start = content.find('<script>', content.find('<script>') + 8) + 8
script2_end = content.find('</script>', script2_start)
script2_content = content[script2_start:script2_end]

# script3: line 4121 (approx)
script3_start = content.find('<script>', script2_end + 9) + 8
script3_end = content.find('</script>', script3_start)
script3_content = content[script3_start:script3_end]

# Combine the quiz logic
quiz_logic = script2_content + '\n' + script3_content

# Now find all function names and global variables to expose them on window
function_pattern = re.compile(r'function\s+([a-zA-Z0-9_]+)\s*\(')
functions = function_pattern.findall(quiz_logic)

var_pattern = re.compile(r'^(?:let|const|var)\s+([a-zA-Z0-9_]+)\s*=', re.MULTILINE)
variables = var_pattern.findall(quiz_logic)

# Create quizEngine.js
import os
os.makedirs('frontend/js/quiz', exist_ok=True)

with open('frontend/js/quiz/quizEngine.js', 'w') as f:
    f.write(quiz_logic)
    f.write('\n\n// --- FACADE BINDINGS (Autogenerated) ---\n')
    
    unique_funcs = list(set(functions))
    for func in unique_funcs:
        f.write(f'window.{func} = {func};\n')
        
    unique_vars = list(set(variables))
    for var in unique_vars:
        # We can't safely rebind let/const references both ways easily without getters/setters,
        # but we can attach them to window so inline scripts can read them.
        # Actually, for full backward compatibility, let's just make them var or attach to window.
        # Replacing top-level let/const with var makes them attach to window if not in a module.
        pass

# Replace let/const with var for top-level variables in quiz_logic?
# Actually, if quizEngine.js is loaded as a normal script (not type="module"), 
# let and const are block scoped, but var is global.
# If we load it as <script src="js/quiz/quizEngine.js"></script>, they are script-scoped,
# meaning inline scripts CAN access them if they are let/const at the top level of the script!
# Wait! Top-level `let` and `const` in a normal `<script>` ARE accessible globally by other normal `<script>` tags, 
# just not attached to `window` object. 
# So we don't need to change them to var, EXCEPT if they are accessed via `window.varName` (they aren't).

# Let's remove the script contents from index.html and replace with the script tag
new_content = content[:script2_start-8] + '<script src="js/quiz/quizEngine.js"></script>\n' + content[script2_end+9:script3_start-8] + content[script3_end+9:]

with open('frontend/index.html', 'w') as f:
    f.write(new_content)

print(f"Extracted {len(unique_funcs)} functions and {len(unique_vars)} variables to quizEngine.js")
